#pragma once

enum class INT_GROUPS
{
    PH,
    MODEM,
    CHIP
};

enum class FRR_MODES
{
    DISABLED,
    INT_STATUS,
    INT_PEND,
    INT_PH_STATUS,
    INT_PH_PEND,
    INT_MODEM_STATUS,
    INT_MODEM_PEND,
    INT_CHIP_STATUS,
    INT_CHIP_PEND,
    CURRENT_STATE,
    LATCHED_RSSI
};

#define RX_FIFO_ALMOST_FULL_PEND 0x01
#define TX_FIFO_ALMOST_EMPTY_PEND 0x02
#define ALT_CRC_ERROR_PEND 0x04
#define CRC_ERROR_PEND 0x08
#define PACKET_RX_PEND 0x10
#define PACKET_SENT_PEND 0x20
#define FILTER_MISS_PEND 0x40
#define FILTER_MATCH_PEND 0x80

#define SPLIT_FIFO_MODE_ENABLE 0X00
#define SPLIT_FIFO_MODE_DISABLE 0X10
